services:
    rusefi.web.listener:
        class: rusefi\web\event\listener
        arguments:
            - @config
            - @request
            - @template
            - @user
        tags:
            - { name: event.listener }
