imports:
    - { resource: tables.yml }
services:
    rusefi.web.listener:
        class: rusefi\web\event\listener
        arguments:
            - @config
            - @request
            - @template
            - @user
            - '@rusefi.web.utils'
        tags:
            - { name: event.listener }
    rusefi.web.utils:
        class: rusefi\web\service\utils
        arguments:
            - '@user'
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '%rusef.web.tables.tokens%'
